/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ButtonSizes,
} from './components/mqi-button/mqi-button';
import {
  TypographySizes,
} from './components/mqi-paragraph/mqi-paragraph';

export namespace Components {
  interface MqiButton {
    /**
    * Button Size
    */
    'size': ButtonSizes;
  }
  interface MqiParagraph {
    /**
    * Paragraph Size
    */
    'size': TypographySizes;
  }
}

declare global {


  interface HTMLMqiButtonElement extends Components.MqiButton, HTMLStencilElement {}
  var HTMLMqiButtonElement: {
    prototype: HTMLMqiButtonElement;
    new (): HTMLMqiButtonElement;
  };

  interface HTMLMqiParagraphElement extends Components.MqiParagraph, HTMLStencilElement {}
  var HTMLMqiParagraphElement: {
    prototype: HTMLMqiParagraphElement;
    new (): HTMLMqiParagraphElement;
  };
  interface HTMLElementTagNameMap {
    'mqi-button': HTMLMqiButtonElement;
    'mqi-paragraph': HTMLMqiParagraphElement;
  }
}

declare namespace LocalJSX {
  interface MqiButton {
    /**
    * Button Size
    */
    'size'?: ButtonSizes;
  }
  interface MqiParagraph {
    /**
    * Paragraph Size
    */
    'size'?: TypographySizes;
  }

  interface IntrinsicElements {
    'mqi-button': MqiButton;
    'mqi-paragraph': MqiParagraph;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'mqi-button': LocalJSX.MqiButton & JSXBase.HTMLAttributes<HTMLMqiButtonElement>;
      'mqi-paragraph': LocalJSX.MqiParagraph & JSXBase.HTMLAttributes<HTMLMqiParagraphElement>;
    }
  }
}


